name: Deploy Theme
on:
  push:
    branches:
      - master
      - main
      - 1.5.0_branch
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Zip theme files
        run: zip -r source_custom.zip .
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-name: "source_custom"
          file: ./source_custom.zip
